[package]
name = "night-systray-example"
version = "0.1.0"
edition = "2021"

[dependencies]
native-windows-derive = "1"
registry = "1"

[dependencies.native-windows-gui]
version = "1"
default-features = false
features = ["cursor", "menu", "message-window", "tray-notification"]
